spring:
  datasource:
    username: root
    password: 997103
    url: jdbc:mysql:///lov?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true